// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matchmaker_common.proto

package com.dota.proto;

public final class MatchmakerCommon {
  private MatchmakerCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code MatchType}
   */
  public enum MatchType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MATCH_TYPE_CASUAL = 0;</code>
     */
    MATCH_TYPE_CASUAL(0, 0),
    /**
     * <code>MATCH_TYPE_COOP_BOTS = 1;</code>
     */
    MATCH_TYPE_COOP_BOTS(1, 1),
    /**
     * <code>MATCH_TYPE_TEAM_RANKED = 2;</code>
     */
    MATCH_TYPE_TEAM_RANKED(2, 2),
    /**
     * <code>MATCH_TYPE_LEGACY_SOLO_QUEUE = 3;</code>
     */
    MATCH_TYPE_LEGACY_SOLO_QUEUE(3, 3),
    /**
     * <code>MATCH_TYPE_COMPETITIVE = 4;</code>
     */
    MATCH_TYPE_COMPETITIVE(4, 4),
    /**
     * <code>MATCH_TYPE_WEEKEND_TOURNEY = 5;</code>
     */
    MATCH_TYPE_WEEKEND_TOURNEY(5, 5),
    /**
     * <code>MATCH_TYPE_CASUAL_1V1 = 6;</code>
     */
    MATCH_TYPE_CASUAL_1V1(6, 6),
    ;

    /**
     * <code>MATCH_TYPE_CASUAL = 0;</code>
     */
    public static final int MATCH_TYPE_CASUAL_VALUE = 0;
    /**
     * <code>MATCH_TYPE_COOP_BOTS = 1;</code>
     */
    public static final int MATCH_TYPE_COOP_BOTS_VALUE = 1;
    /**
     * <code>MATCH_TYPE_TEAM_RANKED = 2;</code>
     */
    public static final int MATCH_TYPE_TEAM_RANKED_VALUE = 2;
    /**
     * <code>MATCH_TYPE_LEGACY_SOLO_QUEUE = 3;</code>
     */
    public static final int MATCH_TYPE_LEGACY_SOLO_QUEUE_VALUE = 3;
    /**
     * <code>MATCH_TYPE_COMPETITIVE = 4;</code>
     */
    public static final int MATCH_TYPE_COMPETITIVE_VALUE = 4;
    /**
     * <code>MATCH_TYPE_WEEKEND_TOURNEY = 5;</code>
     */
    public static final int MATCH_TYPE_WEEKEND_TOURNEY_VALUE = 5;
    /**
     * <code>MATCH_TYPE_CASUAL_1V1 = 6;</code>
     */
    public static final int MATCH_TYPE_CASUAL_1V1_VALUE = 6;


    public final int getNumber() { return value; }

    public static MatchType valueOf(int value) {
      switch (value) {
        case 0: return MATCH_TYPE_CASUAL;
        case 1: return MATCH_TYPE_COOP_BOTS;
        case 2: return MATCH_TYPE_TEAM_RANKED;
        case 3: return MATCH_TYPE_LEGACY_SOLO_QUEUE;
        case 4: return MATCH_TYPE_COMPETITIVE;
        case 5: return MATCH_TYPE_WEEKEND_TOURNEY;
        case 6: return MATCH_TYPE_CASUAL_1V1;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MatchType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MatchType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MatchType>() {
            public MatchType findValueByNumber(int number) {
              return MatchType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.dota.proto.MatchmakerCommon.getDescriptor().getEnumTypes().get(0);
    }

    private static final MatchType[] VALUES = values();

    public static MatchType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MatchType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MatchType)
  }

  /**
   * Protobuf enum {@code DOTABotDifficulty}
   */
  public enum DOTABotDifficulty
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BOT_DIFFICULTY_PASSIVE = 0;</code>
     */
    BOT_DIFFICULTY_PASSIVE(0, 0),
    /**
     * <code>BOT_DIFFICULTY_EASY = 1;</code>
     */
    BOT_DIFFICULTY_EASY(1, 1),
    /**
     * <code>BOT_DIFFICULTY_MEDIUM = 2;</code>
     */
    BOT_DIFFICULTY_MEDIUM(2, 2),
    /**
     * <code>BOT_DIFFICULTY_HARD = 3;</code>
     */
    BOT_DIFFICULTY_HARD(3, 3),
    /**
     * <code>BOT_DIFFICULTY_UNFAIR = 4;</code>
     */
    BOT_DIFFICULTY_UNFAIR(4, 4),
    /**
     * <code>BOT_DIFFICULTY_INVALID = 5;</code>
     */
    BOT_DIFFICULTY_INVALID(5, 5),
    /**
     * <code>BOT_DIFFICULTY_EXTRA1 = 6;</code>
     */
    BOT_DIFFICULTY_EXTRA1(6, 6),
    /**
     * <code>BOT_DIFFICULTY_EXTRA2 = 7;</code>
     */
    BOT_DIFFICULTY_EXTRA2(7, 7),
    /**
     * <code>BOT_DIFFICULTY_EXTRA3 = 8;</code>
     */
    BOT_DIFFICULTY_EXTRA3(8, 8),
    ;

    /**
     * <code>BOT_DIFFICULTY_PASSIVE = 0;</code>
     */
    public static final int BOT_DIFFICULTY_PASSIVE_VALUE = 0;
    /**
     * <code>BOT_DIFFICULTY_EASY = 1;</code>
     */
    public static final int BOT_DIFFICULTY_EASY_VALUE = 1;
    /**
     * <code>BOT_DIFFICULTY_MEDIUM = 2;</code>
     */
    public static final int BOT_DIFFICULTY_MEDIUM_VALUE = 2;
    /**
     * <code>BOT_DIFFICULTY_HARD = 3;</code>
     */
    public static final int BOT_DIFFICULTY_HARD_VALUE = 3;
    /**
     * <code>BOT_DIFFICULTY_UNFAIR = 4;</code>
     */
    public static final int BOT_DIFFICULTY_UNFAIR_VALUE = 4;
    /**
     * <code>BOT_DIFFICULTY_INVALID = 5;</code>
     */
    public static final int BOT_DIFFICULTY_INVALID_VALUE = 5;
    /**
     * <code>BOT_DIFFICULTY_EXTRA1 = 6;</code>
     */
    public static final int BOT_DIFFICULTY_EXTRA1_VALUE = 6;
    /**
     * <code>BOT_DIFFICULTY_EXTRA2 = 7;</code>
     */
    public static final int BOT_DIFFICULTY_EXTRA2_VALUE = 7;
    /**
     * <code>BOT_DIFFICULTY_EXTRA3 = 8;</code>
     */
    public static final int BOT_DIFFICULTY_EXTRA3_VALUE = 8;


    public final int getNumber() { return value; }

    public static DOTABotDifficulty valueOf(int value) {
      switch (value) {
        case 0: return BOT_DIFFICULTY_PASSIVE;
        case 1: return BOT_DIFFICULTY_EASY;
        case 2: return BOT_DIFFICULTY_MEDIUM;
        case 3: return BOT_DIFFICULTY_HARD;
        case 4: return BOT_DIFFICULTY_UNFAIR;
        case 5: return BOT_DIFFICULTY_INVALID;
        case 6: return BOT_DIFFICULTY_EXTRA1;
        case 7: return BOT_DIFFICULTY_EXTRA2;
        case 8: return BOT_DIFFICULTY_EXTRA3;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DOTABotDifficulty>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DOTABotDifficulty>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DOTABotDifficulty>() {
            public DOTABotDifficulty findValueByNumber(int number) {
              return DOTABotDifficulty.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.dota.proto.MatchmakerCommon.getDescriptor().getEnumTypes().get(1);
    }

    private static final DOTABotDifficulty[] VALUES = values();

    public static DOTABotDifficulty valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DOTABotDifficulty(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DOTABotDifficulty)
  }

  /**
   * Protobuf enum {@code MatchLanguages}
   */
  public enum MatchLanguages
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MATCH_LANGUAGE_INVALID = 0;</code>
     */
    MATCH_LANGUAGE_INVALID(0, 0),
    /**
     * <code>MATCH_LANGUAGE_ENGLISH = 1;</code>
     */
    MATCH_LANGUAGE_ENGLISH(1, 1),
    /**
     * <code>MATCH_LANGUAGE_RUSSIAN = 2;</code>
     */
    MATCH_LANGUAGE_RUSSIAN(2, 2),
    /**
     * <code>MATCH_LANGUAGE_CHINESE = 3;</code>
     */
    MATCH_LANGUAGE_CHINESE(3, 3),
    /**
     * <code>MATCH_LANGUAGE_KOREAN = 4;</code>
     */
    MATCH_LANGUAGE_KOREAN(4, 4),
    /**
     * <code>MATCH_LANGUAGE_SPANISH = 5;</code>
     */
    MATCH_LANGUAGE_SPANISH(5, 5),
    /**
     * <code>MATCH_LANGUAGE_PORTUGUESE = 6;</code>
     */
    MATCH_LANGUAGE_PORTUGUESE(6, 6),
    ;

    /**
     * <code>MATCH_LANGUAGE_INVALID = 0;</code>
     */
    public static final int MATCH_LANGUAGE_INVALID_VALUE = 0;
    /**
     * <code>MATCH_LANGUAGE_ENGLISH = 1;</code>
     */
    public static final int MATCH_LANGUAGE_ENGLISH_VALUE = 1;
    /**
     * <code>MATCH_LANGUAGE_RUSSIAN = 2;</code>
     */
    public static final int MATCH_LANGUAGE_RUSSIAN_VALUE = 2;
    /**
     * <code>MATCH_LANGUAGE_CHINESE = 3;</code>
     */
    public static final int MATCH_LANGUAGE_CHINESE_VALUE = 3;
    /**
     * <code>MATCH_LANGUAGE_KOREAN = 4;</code>
     */
    public static final int MATCH_LANGUAGE_KOREAN_VALUE = 4;
    /**
     * <code>MATCH_LANGUAGE_SPANISH = 5;</code>
     */
    public static final int MATCH_LANGUAGE_SPANISH_VALUE = 5;
    /**
     * <code>MATCH_LANGUAGE_PORTUGUESE = 6;</code>
     */
    public static final int MATCH_LANGUAGE_PORTUGUESE_VALUE = 6;


    public final int getNumber() { return value; }

    public static MatchLanguages valueOf(int value) {
      switch (value) {
        case 0: return MATCH_LANGUAGE_INVALID;
        case 1: return MATCH_LANGUAGE_ENGLISH;
        case 2: return MATCH_LANGUAGE_RUSSIAN;
        case 3: return MATCH_LANGUAGE_CHINESE;
        case 4: return MATCH_LANGUAGE_KOREAN;
        case 5: return MATCH_LANGUAGE_SPANISH;
        case 6: return MATCH_LANGUAGE_PORTUGUESE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MatchLanguages>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MatchLanguages>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MatchLanguages>() {
            public MatchLanguages findValueByNumber(int number) {
              return MatchLanguages.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.dota.proto.MatchmakerCommon.getDescriptor().getEnumTypes().get(2);
    }

    private static final MatchLanguages[] VALUES = values();

    public static MatchLanguages valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MatchLanguages(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MatchLanguages)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027matchmaker_common.proto*\321\001\n\tMatchType\022" +
      "\025\n\021MATCH_TYPE_CASUAL\020\000\022\030\n\024MATCH_TYPE_COO" +
      "P_BOTS\020\001\022\032\n\026MATCH_TYPE_TEAM_RANKED\020\002\022 \n\034" +
      "MATCH_TYPE_LEGACY_SOLO_QUEUE\020\003\022\032\n\026MATCH_" +
      "TYPE_COMPETITIVE\020\004\022\036\n\032MATCH_TYPE_WEEKEND" +
      "_TOURNEY\020\005\022\031\n\025MATCH_TYPE_CASUAL_1V1\020\006*\204\002" +
      "\n\021DOTABotDifficulty\022\032\n\026BOT_DIFFICULTY_PA" +
      "SSIVE\020\000\022\027\n\023BOT_DIFFICULTY_EASY\020\001\022\031\n\025BOT_" +
      "DIFFICULTY_MEDIUM\020\002\022\027\n\023BOT_DIFFICULTY_HA" +
      "RD\020\003\022\031\n\025BOT_DIFFICULTY_UNFAIR\020\004\022\032\n\026BOT_D",
      "IFFICULTY_INVALID\020\005\022\031\n\025BOT_DIFFICULTY_EX" +
      "TRA1\020\006\022\031\n\025BOT_DIFFICULTY_EXTRA2\020\007\022\031\n\025BOT" +
      "_DIFFICULTY_EXTRA3\020\010*\326\001\n\016MatchLanguages\022" +
      "\032\n\026MATCH_LANGUAGE_INVALID\020\000\022\032\n\026MATCH_LAN" +
      "GUAGE_ENGLISH\020\001\022\032\n\026MATCH_LANGUAGE_RUSSIA" +
      "N\020\002\022\032\n\026MATCH_LANGUAGE_CHINESE\020\003\022\031\n\025MATCH" +
      "_LANGUAGE_KOREAN\020\004\022\032\n\026MATCH_LANGUAGE_SPA" +
      "NISH\020\005\022\035\n\031MATCH_LANGUAGE_PORTUGUESE\020\006B\020\n" +
      "\016com.dota.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
